### ISSUE TITLE
The Web App is static

### ISSUE THREAD

**Issue by Bilalzip** [gauravsingh94/Full-Stack-E-Commerce-Website-Monorepo#2]
I have opened the app on my machine, there is no any functionality in this web app only a single page with only a few images. please review and make neccessary changes

**Comment by gauravsingh94** [comment]
@Bilalzip The website is not completed yet. I am making it as project but due to other work i did't get the time to work on it.
i will work on this and complete it.
any contribution to this project will be appriciated.
